import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthProvider } from './authContext'
import NavBar from './navbar'
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const classesBody = "min-h-screen flex flex-col " + inter.className;

  return (
    <html lang="en">
      <body className={classesBody}>
        <AuthProvider>
          <div className="grow flex flex-col">
            <NavBar />
            <div className="grow flex flex-col justify-center p-5">
            {children}
            </div>
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
