import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthProvider } from '@/contexts/authContext'
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';



import NavBar from '@/components/navbar';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'es'}];
}

export interface RootLayoutProps {
  children: React.ReactNode,
  params: {
    locale: string
  }
}

export default async function RootLayout(props: RootLayoutProps) {

  const children = props.children;
  const locale = props.params.locale;

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  const classesBody = "min-h-screen flex flex-col " + inter.className;

  return (
    <html lang={locale}>
      <body className={classesBody}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AuthProvider>
            <div className="grow flex flex-col">
              <NavBar />
              <div className="grow flex flex-col justify-center p-5">
                {children}
              </div>
              <Footer />
            </div>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
